#!/bin/bash

function off()
{
	echo "usage: $0 source.b [-o <output>]"
	exit
}

if [ $# != 1 -a $# != 3 ]; then
	off
elif [ $# == 3 ]; then 
	if [ $2"y" == "-oy" ]; then
		OUT=$3
	else
		off
	fi
else
	OUT="a.out"
fi

/usr/bin/preprocessor $1 > temp.i
/usr/bin/compiler temp.i  > temp.s
as temp.s -o temp.o
ld -dynamic-linker /lib64/ld-linux-x86-64.so.2 -L/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/ /root/BICIB/brainfuck/src/entry/en.o temp.o /usr/lib64/crt1.o  /usr/lib64/crti.o  /usr/lib64/crtn.o -lc -o $OUT
rm -f temp.i temp.s temp.o
