
all:
install:
	cp /root/BICIB/brainfuck/bin/interpreter /usr/bin/interpreter
	cp /root/BICIB/brainfuck/bin/preprocessor /usr/bin/preprocessor
	cp /root/BICIB/brainfuck/bin/compiler /usr/bin/compiler
	cp bfi /usr/bin/
	cp bfc /usr/bin/
